feat: add be-web chart
casavo/charts pull request #2
Opened 2022-05-11 11:22 UTC by gi0baro

SSIA

2022-05-11 13:05 UTC, edubacco requested changes
also missing `PodMonitor` resource

2022-05-11 13:34 UTC, gi0baro commented on charts/be-web/templates/worker.yaml
> +{{- end }}
workers are not supposed to have endpoints..

2022-05-11 13:35 UTC, gi0baro commented on charts/be-web/templates/ingress.yaml
> +{{- if .Values.ingress.enabled -}}
can we schedule this for later improvements?

2022-05-11 13:47 UTC, edubacco commented on charts/be-web/Chart.yaml
> +appVersion: latest
As we cannot change this "on the fly" (with values.yaml), what about deleting this and use a custom field in `values.yaml`?

2022-05-11 13:47 UTC, edubacco commented on charts/be-web/templates/_helpers.tpl
> +app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
it's impossible to change the version without changing the chart (see comment in `Chart.yaml`)

2022-05-17 10:50 UTC, gi0baro commented on charts/be-web/Chart.yaml
> +kubeVersion: ">=1.14.0-0"
I think is still fine..

2022-05-17 10:51 UTC, gi0baro commented on charts/be-web/templates/service.yaml
> +    - name: http
I think is not so common, I'm not sure we can support this in a generic chart. I would try to make a dedicated chart for that..

2022-05-18 09:18 UTC, merged