feats from zuul
casavo/charts pull request #41
Opened 2022-07-29 14:44 UTC by AlessandroLorenzi

- feat(web-be): deployment command support
- feat(be-web): cronjob volume and volume mount
- feat(be-web): hooks job volume and volume mount

2022-07-29 15:04 UTC, giuscri requested changes

2022-07-29 15:04 UTC, giuscri commented on charts/be-web/templates/cronjob.yaml
> +              {{- end }}
```suggestion
              {{- with .volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
```

2022-07-29 15:04 UTC, giuscri commented on charts/be-web/templates/cronjob.yaml
> +          {{- end }}
```suggestion
          {{- with .volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
```

2022-07-29 15:04 UTC, giuscri commented on charts/be-web/templates/hooks/job.yaml
> +          {{- end }}
```suggestion
          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
```

2022-07-29 15:04 UTC, giuscri commented on charts/be-web/templates/hooks/job.yaml
> +      {{- end }}
```suggestion
      {{- with .volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

2022-07-29 15:13 UTC, gi0baro requested changes
@AlessandroLorenzi can you please provide use cases (even with links from zuul repo) for:
- deployment command: why you can't use the entrypoint like everything else?
- mounting volumes: where does these volumes come from? mounting such things in hooks is quite dangerous as it might be executed in transient states where those data doesn't exist (yet)

Also, in general, given the changes, I would make a minor, not a patch version

2022-08-01 08:33 UTC, AlessandroLorenzi commented
> @AlessandroLorenzi can you please provide use cases (even with links from zuul repo) for:
> 
>     * deployment command: why you can't use the entrypoint like everything else?

You are right, I could recreate the container. Anyway, command is supported by k8s, so why not?

> 
>     * mounting volumes: where does these volumes come from? mounting such things in hooks is quite dangerous as it might be executed in transient states where those data doesn't exist (yet)
> 

in zuul:

```yaml
      volumes:
      - name: gdrive-service-account
        secret:
          secretName: gdrive-service-account
          optional: false
```

I'ts managed by `kubernetes-app-secrets` repo, so no problem with that.


> 
> Also, in general, given the changes, I would make a minor, not a patch version

👍🏼

2022-08-01 12:18 UTC, closed without merging