feat: use `batch/v1` for cronjob in be-web and be-multisvc
casavo/charts pull request #70
Opened 2023-06-22 10:18 UTC by elleuca

to solve helm warning:

```
batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
```

2023-06-22 10:20 UTC, gi0baro requested changes
You also need to bump the relative versions in `Chart.yaml`

2023-06-22 16:25 UTC, elleuca commented
> You also need to bump the relative versions in `Chart.yaml`

@gi0baro patch or minor?

2023-06-23 08:42 UTC, gi0baro commented
> > You also need to bump the relative versions in `Chart.yaml`
> 
> @gi0baro patch or minor?

I would go with minor

2023-06-27 09:04 UTC, gi0baro approved these changes

2023-06-27 09:06 UTC, merged